# Generated by Django 6.0.7 on 2026-07-29 13:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_customer_created_by_customer_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquirySource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('color', models.CharField(blank=True, default='primary', max_length=30)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enquiry Source',
                'verbose_name_plural': 'Enquiry Sources',
                'db_table': 'enquiry_source',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EnquiryStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('color', models.CharField(default='primary', help_text='Bootstrap color class', max_length=30)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Response Status',
                'verbose_name_plural': 'Response Statuses',
                'db_table': 'enquiry_response_status',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enquiry_no', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('expected_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('enquiry_date', models.DateField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_enquiries', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='customers.customer')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enquiries', to='enquiries.enquirysource')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enquiries', to='enquiries.enquirystatus')),
            ],
            options={
                'verbose_name': 'Enquiry',
                'verbose_name_plural': 'Enquiries',
                'db_table': 'enquiry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response_no', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Medium', max_length=20)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('next_followup_at', models.DateTimeField(blank=True, null=True)),
                ('is_converted', models.BooleanField(default=False)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_responses', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='enquiries.enquiry')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Response',
                'verbose_name_plural': 'Responses',
                'db_table': 'enquiry_response',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting_no', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('meeting_type', models.CharField(choices=[('Office', 'Office'), ('Site Visit', 'Site Visit'), ('Client Place', 'Client Place'), ('Online', 'Online'), ('Phone', 'Phone')], default='Office', max_length=20)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Rescheduled', 'Rescheduled'), ('No Show', 'No Show')], default='Scheduled', max_length=20)),
                ('meeting_date', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_meetings', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='enquiries.response')),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
                'db_table': 'enquiry_meeting',
                'ordering': ['meeting_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('followup_no', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('followup_type', models.CharField(choices=[('Call', 'Call'), ('WhatsApp', 'WhatsApp'), ('Email', 'Email'), ('SMS', 'SMS'), ('Visit', 'Visit'), ('Other', 'Other')], default='Call', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Missed', 'Missed')], default='Pending', max_length=20)),
                ('followup_date', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_followups', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='enquiries.response')),
            ],
            options={
                'verbose_name': 'Follow-up',
                'verbose_name_plural': 'Follow-ups',
                'db_table': 'enquiry_followup',
                'ordering': ['followup_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResponseActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('Created', 'Created'), ('Assigned', 'Assigned'), ('Status Changed', 'Status Changed'), ('Follow Up', 'Follow Up'), ('Meeting', 'Meeting'), ('Note', 'Note'), ('Document', 'Document'), ('Email', 'Email'), ('WhatsApp', 'WhatsApp'), ('SMS', 'SMS'), ('Call', 'Call'), ('Converted', 'Converted'), ('Closed', 'Closed')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('activity_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_activities', to=settings.AUTH_USER_MODEL)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='enquiries.response')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Response Activity',
                'verbose_name_plural': 'Response Activities',
                'db_table': 'enquiry_response_activity',
                'ordering': ['-activity_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ResponseDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('Image', 'Image'), ('PDF', 'PDF'), ('Document', 'Document'), ('Audio', 'Audio'), ('Video', 'Video'), ('Spreadsheet', 'Spreadsheet'), ('Other', 'Other')], default='Other', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='crm/response_documents/%Y/%m/')),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='enquiries.response')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Response Document',
                'verbose_name_plural': 'Response Documents',
                'db_table': 'enquiry_response_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResponseNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField()),
                ('is_private', models.BooleanField(default=True, help_text='Visible only to internal staff.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_notes', to=settings.AUTH_USER_MODEL)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='enquiries.response')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Response Note',
                'verbose_name_plural': 'Response Notes',
                'db_table': 'enquiry_response_note',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResponseStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('color', models.CharField(blank=True, default='primary', max_length=30)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enquiry Status',
                'verbose_name_plural': 'Enquiry Statuses',
                'db_table': 'enquiry_status',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='response',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='enquiries.responsestatus'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['enquiry_no'], name='enquiry_enquiry_e59379_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['status'], name='enquiry_status__adc716_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['source'], name='enquiry_source__3c6846_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['assigned_to'], name='enquiry_assigne_20cc21_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['status'], name='enquiry_mee_status_b12449_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['meeting_date'], name='enquiry_mee_meeting_4cfef9_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['assigned_to'], name='enquiry_mee_assigne_ce122e_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['status'], name='enquiry_fol_status_c012e1_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['followup_date'], name='enquiry_fol_followu_882cd0_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['assigned_to'], name='enquiry_fol_assigne_d0cbb6_idx'),
        ),
        migrations.AddIndex(
            model_name='responseactivity',
            index=models.Index(fields=['response'], name='enquiry_res_respons_1f794f_idx'),
        ),
        migrations.AddIndex(
            model_name='responseactivity',
            index=models.Index(fields=['activity_type'], name='enquiry_res_activit_251a04_idx'),
        ),
        migrations.AddIndex(
            model_name='responseactivity',
            index=models.Index(fields=['activity_at'], name='enquiry_res_activit_9a910c_idx'),
        ),
        migrations.AddIndex(
            model_name='responsedocument',
            index=models.Index(fields=['response'], name='enquiry_res_respons_e6eed9_idx'),
        ),
        migrations.AddIndex(
            model_name='responsedocument',
            index=models.Index(fields=['document_type'], name='enquiry_res_documen_5c8a0e_idx'),
        ),
        migrations.AddIndex(
            model_name='responsedocument',
            index=models.Index(fields=['created_at'], name='enquiry_res_created_a05d0c_idx'),
        ),
        migrations.AddIndex(
            model_name='responsenote',
            index=models.Index(fields=['response'], name='enquiry_res_respons_fd2a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='responsenote',
            index=models.Index(fields=['created_at'], name='enquiry_res_created_3aa6bc_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['response_no'], name='enquiry_res_respons_e6b107_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['status'], name='enquiry_res_status__4893eb_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['assigned_to'], name='enquiry_res_assigne_dfca77_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['is_converted'], name='enquiry_res_is_conv_0eaa15_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['next_followup_at'], name='enquiry_res_next_fo_c3c595_idx'),
        ),
    ]
