# Generated by Django 6.0.7 on 2026-07-24 16:24

import django.db.models.deletion
import mptt.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('location_type', models.CharField(choices=[('COUNTRY', 'Country'), ('STATE', 'State'), ('DISTRICT', 'District'), ('CITY', 'City'), ('LOCALITY', 'Locality'), ('SUBLOCALITY', 'Sub Locality'), ('AREA', 'Area'), ('PINCODE', 'Pincode')], db_index=True, max_length=20)),
                ('postal_code', models.CharField(blank=True, help_text='Required only for PINCODE type', max_length=10, null=True)),
                ('is_top_city', models.BooleanField(default=False)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='utility.location', verbose_name='Parent Location')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['tree_id', 'lft'],
            },
        ),
    ]
