# Generated by Django 6.0.7 on 2026-07-24 17:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_postal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Postal Code',
                'verbose_name_plural': 'Postal Codes',
                'ordering': ['code'],
            },
        ),
        migrations.DeleteModel(
            name='Postal_Code',
        ),
        migrations.RemoveField(
            model_name='location',
            name='postal_code',
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('COUNTRY', 'Country'), ('STATE', 'State'), ('DISTRICT', 'District'), ('CITY', 'City'), ('LOCALITY', 'Locality'), ('SUBLOCALITY', 'Sub Locality'), ('AREA', 'Area')], db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='postalcode',
            name='location',
            field=models.ForeignKey(limit_choices_to={'location_type__in': ['LOCALITY', 'SUBLOCALITY', 'AREA']}, on_delete=django.db.models.deletion.PROTECT, related_name='postal_codes', to='utility.location'),
        ),
    ]
