# Generated by Django 6.0.7 on 2026-07-28 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0006_countrycode_currency_education_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='is_top_city',
            field=models.BooleanField(default=False, help_text='Mark important cities for quick selection.'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('COUNTRY', 'Country'), ('STATE', 'State'), ('DISTRICT_CITY', 'District / City'), ('LOCALITY_AREA', 'Locality / Area'), ('SUBLOCALITY_AREA', 'Sub Locality / Area')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='location',
            field=models.ForeignKey(limit_choices_to={'location_type__in': ['LOCALITY_AREA', 'SUBLOCALITY_AREA']}, on_delete=django.db.models.deletion.PROTECT, related_name='postal_codes', to='utility.location'),
        ),
    ]
