# Generated by Django 6.0.7 on 2026-08-04 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0010_alter_amenity_created_at_alter_amenity_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructionstatus',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='constructionstatus',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='facing',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='facing',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='furnishing',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='furnishing',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='ownershiptype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ownershiptype',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='parkingtype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='parkingtype',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='propertytype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='propertytype',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='unittype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='unittype',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Amenity',
        ),
        migrations.DeleteModel(
            name='ConstructionStatus',
        ),
        migrations.DeleteModel(
            name='Facing',
        ),
        migrations.DeleteModel(
            name='Furnishing',
        ),
        migrations.DeleteModel(
            name='OwnershipType',
        ),
        migrations.DeleteModel(
            name='ParkingType',
        ),
        migrations.DeleteModel(
            name='PropertyType',
        ),
        migrations.DeleteModel(
            name='UnitType',
        ),
    ]
