# Generated by Django 6.0.7 on 2026-07-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('company_admin', 'Company Admin'), ('sales_manager', 'Sales Manager'), ('sales_executive', 'Sales Executive'), ('marketing', 'Marketing'), ('accounts', 'Accounts'), ('support', 'Support'), ('employee', 'Employee')], default='employee', max_length=30),
        ),
    ]
