# Generated by Django 6.0.7 on 2026-07-28 14:31

import ckeditor.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('utility', '0007_alter_location_is_top_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Company Category',
                'verbose_name_plural': 'Company Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='primary', help_text='Bootstrap color (primary, success, warning, danger...)', max_length=30)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon class', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Company Status',
                'verbose_name_plural': 'Company Status',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GoogleMapStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Google Map Status',
                'verbose_name_plural': 'Google Map Status',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['company', 'name']},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='companycontact',
            options={'ordering': ['company', '-is_primary', 'name']},
        ),
        migrations.AlterModelOptions(
            name='companysize',
            options={'ordering': ['min_employee', 'name'], 'verbose_name': 'Company Size', 'verbose_name_plural': 'Company Sizes'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['company', 'name']},
        ),
        migrations.AlterModelOptions(
            name='designation',
            options={'ordering': ['department', 'name']},
        ),
        migrations.RemoveField(
            model_name='branch',
            name='location',
        ),
        migrations.RemoveField(
            model_name='company',
            name='location',
        ),
        migrations.RemoveField(
            model_name='company',
            name='phone',
        ),
        migrations.AddField(
            model_name='branch',
            name='area',
            field=models.ForeignKey(blank=True, limit_choices_to={'location_type': 'SUBLOCALITY_AREA'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branch_area', to='utility.location'),
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.ForeignKey(blank=True, limit_choices_to={'location_type': 'DISTRICT_CITY'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branch_city', to='utility.location'),
        ),
        migrations.AddField(
            model_name='branch',
            name='is_head_office',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='locality',
            field=models.ForeignKey(blank=True, limit_choices_to={'location_type': 'LOCALITY_AREA'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branch_locality', to='utility.location'),
        ),
        migrations.AddField(
            model_name='branch',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='area',
            field=models.ForeignKey(blank=True, limit_choices_to={'location_type': 'SUBLOCALITY_AREA'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companies_area', to='utility.location'),
        ),
        migrations.AddField(
            model_name='company',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.ForeignKey(blank=True, limit_choices_to={'location_type': 'DISTRICT_CITY'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companies_city', to='utility.location'),
        ),
        migrations.AddField(
            model_name='company',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='companies/cover/'),
        ),
        migrations.AddField(
            model_name='company',
            name='google_map',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='locality',
            field=models.ForeignKey(blank=True, limit_choices_to={'location_type': 'LOCALITY_AREA'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companies_locality', to='utility.location'),
        ),
        migrations.AddField(
            model_name='company',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='meta_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='short_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companydocument',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companydocument',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyindustry',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companysize',
            name='max_employee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companysize',
            name='min_employee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='manager_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='branch',
            name='postal_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='utility.postalcode'),
        ),
        migrations.AlterField(
            model_name='company',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='companies.companysize'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='companies.companytype'),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='companies.companyindustry'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='postal_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='utility.postalcode'),
        ),
        migrations.AlterField(
            model_name='companycontact',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.designation'),
        ),
        migrations.AlterField(
            model_name='companycontact',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='companies.companycategory'),
        ),
        migrations.CreateModel(
            name='CompanyGallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='companies/gallery/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='companies.company')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='companies.companystatus'),
        ),
        migrations.AddField(
            model_name='companydocument',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.documenttype'),
        ),
        migrations.AddField(
            model_name='company',
            name='google_business_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.googlemapstatus'),
        ),
    ]
