# Generated by Django 6.0.7 on 2026-09-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_followup_id_alter_meeting_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectivity',
            name='km',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='connectivity',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
