# Generated by Django 6.0.7 on 2026-09-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_connectivity_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectivity',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Connectivity Point', 'verbose_name_plural': 'Connectivity Points'},
        ),
        migrations.RenameField(
            model_name='connectivity',
            old_name='Project',
            new_name='project',
        ),
        migrations.AddField(
            model_name='connectivity',
            name='drive_time',
            field=models.CharField(default='05 Mins', help_text='e.g. 04 Mins', max_length=50),
        ),
        migrations.AddField(
            model_name='connectivity',
            name='metro_time',
            field=models.CharField(default='10 Mins', help_text='e.g. 08 Mins', max_length=50),
        ),
        migrations.AddField(
            model_name='connectivity',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order'),
        ),
        migrations.AddField(
            model_name='connectivity',
            name='progress_percent',
            field=models.PositiveIntegerField(default=25, help_text='Telemetry progress bar width (1 - 100)'),
        ),
        migrations.AddField(
            model_name='connectivity',
            name='radar_angle',
            field=models.FloatField(default=1.5, help_text='Angle in radians (0.1 se 6.2 ke beech)'),
        ),
        migrations.AddField(
            model_name='connectivity',
            name='radar_radius',
            field=models.PositiveIntegerField(default=50, help_text='Center se doori (Value 25 se 120 ke beech rakhein)'),
        ),
        migrations.AddField(
            model_name='connectivity',
            name='subtitle',
            field=models.CharField(blank=True, help_text='e.g. North-South Arterial Corridor', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='connectivity',
            name='walk_time',
            field=models.CharField(default='15 Mins', help_text='e.g. 20 Mins ya -- Mins', max_length=50),
        ),
        migrations.AlterField(
            model_name='connectivity',
            name='km',
            field=models.CharField(blank=True, help_text='e.g. 2.5 KM', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='connectivity',
            name='title',
            field=models.CharField(help_text='e.g. Western Express Highway', max_length=150),
        ),
    ]
