# Generated by Django 6.0.7 on 2026-09-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_connectivity_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectivity',
            name='drive_time',
            field=models.CharField(blank=True, default='05 Mins', help_text='e.g. 04 Mins', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='connectivity',
            name='metro_time',
            field=models.CharField(blank=True, default='10 Mins', help_text='e.g. 08 Mins', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='connectivity',
            name='walk_time',
            field=models.CharField(blank=True, default='15 Mins', help_text='e.g. 20 Mins ya -- Mins', max_length=50, null=True),
        ),
    ]
