# Generated by Django 6.0.7 on 2026-09-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_alter_connectivity_drive_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Gallery Image', 'verbose_name_plural': 'Gallery Images'},
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='Project',
            new_name='project',
        ),
        migrations.AddField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('all', 'All'), ('exterior', 'Exterior & Architecture'), ('interior', 'Luxury Interiors'), ('amenities', 'Amenities & Landscape'), ('construction', 'Construction Updates')], default='exterior', max_length=50),
        ),
        migrations.AddField(
            model_name='gallery',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
