# Generated by Django 6.0.7 on 2026-09-30 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_developerimpactmetric'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developerimpactmetric',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Impact Metric', 'verbose_name_plural': 'Developer Impact Metrics'},
        ),
        migrations.AlterField(
            model_name='developerimpactmetric',
            name='icon',
            field=models.CharField(blank=True, help_text='Example: "fa-solid fa-building"', max_length=500, null=True, verbose_name='Font Awesome Icon'),
        ),
        migrations.AlterField(
            model_name='developerimpactmetric',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='developerimpactmetric',
            name='setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='developer_impact_metrics', to='properties.developer', verbose_name='Developer'),
        ),
        migrations.AlterField(
            model_name='developerimpactmetric',
            name='title',
            field=models.CharField(blank=True, help_text='Example: "Completed Projects"', max_length=255, null=True, verbose_name='Metric Title'),
        ),
        migrations.AlterField(
            model_name='developerimpactmetric',
            name='value',
            field=models.CharField(blank=True, help_text='Example: "25+", "10,000+" or "95%"', max_length=100, null=True, verbose_name='Metric Value'),
        ),
    ]
