# Generated by Django 6.0.7 on 2026-09-30 10:39

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_alter_developerimpactmetric_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='read_more',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
