# Generated by Django 6.0.7 on 2026-09-09 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_about_setting_alter_about_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title3',
        ),
    ]
