# Generated by Django 6.0.7 on 2026-09-13 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='testmonial_bg',
            new_name='Virtual_bg',
        ),
    ]
