# Generated by Django 6.0.7 on 2026-09-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_testmonial_bg_setting_virtual_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='virtual_360_title',
            field=models.CharField(blank=True, default='360° Airspace Panorama', help_text='Heading/Title for 360 Section', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='virtual_360_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
