# Generated by Django 6.0.7 on 2026-09-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_inquiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={},
        ),
        migrations.RenameField(
            model_name='inquiry',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='city',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='preferred_slot',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
