# Generated by Django 6.0.7 on 2026-09-14 12:28

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_inquiry_options_rename_full_name_inquiry_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='privacy_policy',
            new_name='disclaimer_content',
        ),
        migrations.AddField(
            model_name='setting',
            name='disclaimer_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='privacy_policy_content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='privacy_policy_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
