# Generated by Django 6.0.7 on 2026-09-16 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_privacy_policy_setting_disclaimer_content_and_more'),
        ('properties', '0010_alter_gallery_options_rename_project_gallery_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceBreakupInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField(blank=True, null=True)),
                ('property_type', models.CharField(blank=True, max_length=100, null=True)),
                ('property_area', models.CharField(blank=True, max_length=100, null=True)),
                ('property_price', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_breakup_inquiries', to='properties.project')),
            ],
        ),
    ]
