# Generated by Django 6.0.7 on 2026-09-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_pricebreakupinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='linkexplore',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
