# Generated by Django 6.0.7 on 2026-09-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_slider_button_link_remove_slider_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='google_label',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
