# Generated by Django 6.0.7 on 2026-07-31 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_branch_created_by_branch_updated_by_and_more'),
        ('response', '0001_initial'),
        ('utility', '0009_alter_amenity_created_by_alter_amenity_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ['-created_at'], 'verbose_name': 'Response', 'verbose_name_plural': '0. Responses'},
        ),
        migrations.AddField(
            model_name='followup',
            name='followup_no',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_no',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='response',
            name='response_no',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['response_no'], name='response_re_respons_b05e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['lead_source'], name='response_re_lead_so_d6d130_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['is_converted'], name='response_re_is_conv_4725af_idx'),
        ),
    ]
