# Generated by Django 6.0.7 on 2026-07-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0002_alter_response_options_followup_followup_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='followup_no',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_no',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='response_no',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
