# Generated by Django 6.0.7 on 2026-07-31 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0003_alter_followup_followup_no_alter_meeting_meeting_no_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followup',
            options={'ordering': ('-followup_date',), 'verbose_name': 'Follow Up', 'verbose_name_plural': '2. Follow Ups'},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ('-meeting_date',), 'verbose_name': 'Meeting', 'verbose_name_plural': '1. Meetings'},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ('-created_at',), 'verbose_name': 'Response', 'verbose_name_plural': '0. Responses'},
        ),
        migrations.AlterField(
            model_name='followup',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_response_followups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followup',
            name='response',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followup', to='response.response'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='status',
            field=models.CharField(choices=[('New Followup', 'New Followup'), ('Re Followup', 'Re Followup'), ('Cancelled', 'Cancelled'), ('Deal Done', 'Deal Done')], default='New Followup', max_length=25),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_response_meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='response',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='response.response'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('New Meeting', 'New Meeting'), ('Re Meeting', 'Re Meeting'), ('Cancelled', 'Cancelled'), ('Deal Done', 'Deal Done')], default='New Meeting', max_length=25),
        ),
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Meeting', 'Meeting'), ('Follow_Up', 'Follow Up'), ('Meeting_FollowUp', 'Meeting / Follow Up'), ('Not_received', 'Not Received'), ('Software_company', 'Software Company'), ('For_job', 'For Job'), ('Training', 'Training'), ('Fake_lead', 'Fake Lead'), ('Deal_close', 'Deal Close')], db_index=True, default='New', max_length=25),
        ),
    ]
