# Generated by Django 6.0.7 on 2026-09-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties_utility', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectamenities',
            name='image',
        ),
        migrations.AddField(
            model_name='projectamenities',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
